name: Trigger MacroDroid via ADB

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  trigger-macro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ADB
        run: |
          sudo apt-get update
          sudo apt-get install -y android-tools-adb

      - name: Connect to phone via ADB
        run: |
          adb connect YOUR_PHONE_IP:5555

      - name: Trigger MacroDroid macro
        run: |
          adb shell am broadcast \
            -a com.arlosoft.macrodroid.ACTION_TRIGGER_MACRO \
            --es macro_name "макро_1"
